JAP:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: java_ai_practiceroom
    username: root
    password: 123456
minio:
    endpoint: http://192.168.100.128:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: java-ai-practiceroom